### Send a ping to receive pong
POST http://localhost:3000

{"type":"ping"}

### Send invalid route
POST http://localhost:3000

### Reflect request (with added middleware data)
POST http://localhost:3000

{"type":"echo"}
